apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  labels:
    app.kubernetes.io/name: codeserver
    app.kubernetes.io/instance: codeserver-sample
    app.kubernetes.io/part-of: code-server-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: code-server-operator
  name: codeserver-sample
spec:
  # TODO(user): Add fields here
